### ISSUE TITLE
Document rules for GitHub crawling in README

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/LimeBootstrapServices#13]
How is the crawling done? (After the changes that we are about to do)

**Comment by LarsCJensen** [comment]
Is the current enough? Are you checking the wrong branch?

https://github.com/Lundalogik/LimeBootstrapServices/tree/LBS-service3.1

**Comment by justFredster** [comment]
I updated the description! I meant after the changes that we are about to do.

**Comment by LarsCJensen** [comment]
Perhaps there should be a description of the .limestore.json file somewhere? I've updated the readme but there should perhaps be a prime link which accompanies the change.
