### ISSUE TITLE
Possible to add several add-ons in the same metadata file, for situations where one repository should be displayed as several entries in the Lime Store

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/LimeBootstrapServices#17]
One addon should be used on several entries in Lime store. Ex. Visma Admin (Erp Connector) FortNox (Erp Connector).

**Comment by LarsCJensen** [comment]
Difficult to grasp how this is going to work since it crawls repos. Perhaps there could be a dict with different unique names for the same repo... What do you think @justFredster

**Comment by justFredster** [comment]
I don't know the code that well. Perhaps it would be possible to loop over the array of add-ons in the JSON and create several database rows in the postgre db on that?
