### ISSUE TITLE
If DisplayName is not set it can't find the addon when crawling Github

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/LimeBootstrapServices#21]
How should that be handled? Should it ignore the addon or use the repo name?

**Comment by LarsCJensen** [comment]
If metadata.json isn't found I will remove the addon from the json since it won't be compatible with Lime Store even if it was to be shown.

**Comment by LarsCJensen** [comment]
Correction, if Metadata.json is there but lacks displayName set it will use repo name.

**Comment by justFredster** [comment]
metadata.json should no longer be used. Or am I missing something? :) @LarsCJensen

**Comment by LarsCJensen** [comment]
If .limestore.md/json does not contain displayname, it will use the repo name. Else it would fail.

**Comment by justFredster** [comment]
If that is the case then skip the add-on and don’t add stuff to the postgresql db I’d say. Better to skip if configuration is not correct instead of falling back to something that would not look good in Lime Store anyway.
